-- MySQL Script generated by MySQL Workbench
-- Sun May 25 12:23:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema formsmaps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formsmaps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formsmaps` DEFAULT CHARACTER SET utf8mb4 ;
USE `formsmaps` ;

-- -----------------------------------------------------
-- Table `formsmaps`.`dataformsuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formsmaps`.`dataformsuser` (
  `id_Forms` INT(11) NOT NULL,
  `UserProgram` VARCHAR(100) NOT NULL,
  `UserSemester` INT NOT NULL,
  `UserStyudyDay` VARCHAR(50) NOT NULL,
  `UserAger` INT NOT NULL,
  `UserLocality` VARCHAR(45) NOT NULL,
  `UserNeighborhood` VARCHAR(45) NOT NULL,
  `UserTransport` VARCHAR(45) NOT NULL,
  `UserSecurityPersence` VARCHAR(45) NOT NULL,
  `UserSafetyReviewAvRojas26` VARCHAR(45) NOT NULL,
  `UserSafetyReviewAvRojas63` VARCHAR(45) NOT NULL,
  `UserSafetyReviewAvRojas53yAvBoyaca` VARCHAR(45) NOT NULL,
  `UserTheftVictim` VARCHAR(45) NOT NULL,
  `UserLocationTheft` POINT NOT NULL,
  `UserDayOfTheFacts` VARCHAR(45) NOT NULL,
  `UserTimeForFacts` VARCHAR(45) NOT NULL,
  `dataformsusercol` TIME NOT NULL,
  `dataformsusercol1` VARCHAR(45) NOT NULL,
  `UserStolenObjects` VARCHAR(45) NOT NULL,
  `UserHowManyCriminals` VARCHAR(45) NOT NULL,
  `UserWeaponType` VARCHAR(45) NOT NULL,
  `UserDisplacementOfThieves` VARCHAR(45) NOT NULL,
  `UserWhoWasHeWith` VARCHAR(45) NOT NULL,
  `UserTypeOfInjuries` VARCHAR(45) NOT NULL,
  `dataformsusercol2` VARCHAR(45) NOT NULL,
  `UserAfterTheEvents` VARCHAR(45) NOT NULL,
  `UserRecommendation` VARCHAR(100) NULL,
  PRIMARY KEY (`id_Forms`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
