-- MySQL Script generated by MySQL Workbench
-- Sun May 25 23:21:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema formsmaps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema formsmaps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formsmaps` DEFAULT CHARACTER SET utf8mb4 ;
USE `formsmaps` ;

-- -----------------------------------------------------
-- Table `formsmaps`.`dataformsuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `formsmaps`.`dataformsuser` (
  `id_Forms` INT(11) NOT NULL AUTO_INCREMENT,
  `Program` VARCHAR(100) NOT NULL,
  `Semester` INT(11) NOT NULL,
  `Day` VARCHAR(50) NOT NULL,
  `Age` INT(11) NOT NULL,
  `Locality` VARCHAR(45) NOT NULL,
  `Neighborhood` VARCHAR(45) NOT NULL,
  `Transport` VARCHAR(45) NOT NULL,
  `Perception` VARCHAR(45) NOT NULL,
  `AvRojas26` VARCHAR(45) NOT NULL,
  `AvRojas63` VARCHAR(45) NOT NULL,
  `AvRojas53yBoyaca` VARCHAR(45) NOT NULL,
  `Intimidation` VARCHAR(45) NOT NULL,
  `MapTheft` POINT NOT NULL,
  `DayFacts` VARCHAR(45) NOT NULL,
  `TimeFacts` TIME NOT NULL,
  `StolenObject` VARCHAR(45) NOT NULL,
  `NumberOfOffenders` VARCHAR(45) NOT NULL,
  `WeaponType` VARCHAR(45) NOT NULL,
  `DisplacementOfPerpetrators` VARCHAR(45) NOT NULL,
  `StateAtTheMoment` VARCHAR(45) NOT NULL,
  `TypeOfLesson` VARCHAR(100) NOT NULL,
  `AfterTheEvents` VARCHAR(45) NOT NULL,
  `Recommendation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Forms`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
